dist: trusty
sudo: false
language: cpp
compiler: gcc

os: linux

services:
  - docker

before_install:
  - docker pull danoan/graphflow:dgtal
  - docker build . -t graphflow:build
  
script:
  - docker run graphflow:build /bin/sh -c /app/scripts/generate-coverage.sh

after_success:
  - ci_env=$(bash <(curl -s https://codecov.io/env) )
  - ci_post_cov="bash <(curl -s https://codecov.io/bash) -t ee9f5805-fb7f-4d91-8d6b-8a2e79e6e788"
  - docker run $ci_env graphflow:build bash -c "$ci_post_cov"
