codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - app/report-generator/*.
  - build-tools/.*
  - catch/.*
  - deps/.*
  - ext/.*
  - lab/.*  # ignore folders and all its contents
  - modules/contour-correction/test/.*
  - modules/core/test/.*
  - modules/io/seed/test/.*
  - modules/shape-evolution/test/.*
  - modules/utils/test/.*
  - modules/contour-correction/src/model/image.GMM.cpp
