FROM ubuntu:18.04

RUN apt-get update; apt-get install -y \
cmake \
# doxygen \
graphviz \
g++ \
# gcc \
git \
gfortran \
libgtk2.0-dev \
libgraphicsmagick++1-dev \
make \
qt5-default \
zlib1g-dev \
wget \
pkg-config && apt-get -y clean
