#Use an official Python runtime as a parent image
FROM ubuntu:18.04

RUN apt-get update; apt-get install -y doxygen \
graphviz \
cmake \
gcc \
g++ \
make \
gfortran \
git \
zlib1g-dev \
wget \
libgtk2.0-dev \
pkg-config && apt-get -y clean
