#ifndef GRAPH_FLOW_SUMMARY_FLOW_SUMMARY_FLOW_TYPES_H
#define GRAPH_FLOW_SUMMARY_FLOW_SUMMARY_FLOW_TYPES_H

namespace SummaryFlow {
enum ImageOutputType { SVG, EPS };
}

#endif  // GRAPH_FLOW_SUMMARY_FLOW_SUMMARY_FLOW_TYPES_H
